### ISSUE TITLE
lksudoku's Bug fixes

### ISSUE THREAD

**Issue by SudokuMonster** [SudokuMonster/SukakuExplainer#46]
Looking at Iksudoko Fixed14 code from his repository. There are few remarks:
1.  - [x] Added a batched-techniques solver. It applys all hints that share the lowest ra
ting.
```
accumulate until higher rating is added
apply all concurrent moves of lowest rating

The mode also gives lower ratings in cases where one UR/UL destroys another UR/UL
when applied, see puzzles
..1.36..4.6.8....37...........3...8..2..9..6..7...2...........85....1.9.4..95.1..
6.7.8.9.3.........3..2.4..5..5...4..7...2...1..9...7..9..5.2..7.........1.8.7.5.6
.1.......2.....3.....4.567...38.61.............57.29...826.1.....7....5.........9
9....2.7...58..2...2..9...6.4.....8...3.7...15.....9...8...34..7..9....3..1.8..5.
.1...9...34.........2.45......8..6.5..6...7..8.5..2......17.8.........43...6...2.
....8......23.45...6.....9.4.......6.3.....1...87.53...1..6..4.7...9...2.........
...........43.92...125.736..43...95...........57...18..754.183...97.25...........
9.8...4...6...3...4...7...3...1.2.3...5...1...4.3.9...6...9...1...7...8...2...3.4
.....47...2..9..1.4..2.....5...8.4...6.3.9.8...1.6...9.....1..3.1..7..6...54.....
..1..2..3.2..1.4..3..9...7...6.....4.1..9..3.8.....9...3...4..7..4.5..9.6..7..2..

In addition, batch mode seems to solve the problem of different isomorphs having
different rating, see the following two transposed puzzles:
.1...2...34.........2.57......3..1.7..9...4..1.5..8......69.3.........62...7...9.
.3...1...14.........2.95......3..6.7..5...9..2.7..8......14.3.........69...7...2.
```
2. - [x] There is a fix to BUG type 2 issue
```
Examples of puzzles affected by bug:
..4..6..5.1..8.6..5..4...9...5.....9.9..2..7.7.....2...7...2..6..8.6..1.4..8..7..
1.2...3.......2.4.5...6...2...3...7...6.5.8...8...9...4...1...5.3.8.......7...9.6
```
3. - [ ] There is chain sorting improvement aimed at guaranteeing the same chain output everytime
```
We sort the removable potentials so that all runs will yield the
same resulting chains, if not sorted, same puzzle may get different chains
when there are different chains for same contradition, thus causing different
rating of same puzzle at different times

example of puzzle affected by bug/old code:
2..3....5.....473.....9..1......1.9.....7.4...6.8....34.5......6..5......79.....8

The following puzzles are examples that can be solved with shorter chains
..12......3...45..6......7.2..1...8.....2.....9......3.5......9..76...1......34.7
1..2..3......1..4...5..6..78.....2...3..9..8...4.....12..8..7...1..5......3..4..6
..1..23...4..5..6.7.......8...5.......5.4.9.......8...8.......7.6..9..4...31..2..

The following puzzles are an example for relabeling rating change bug
5.....2...9.3.....8.6.....17..2......8..9......4..1.6..7.5..3....2.8..4.4....27.9
5.....2...1.3.....8.6.....97..2......8..1......4..9.6..7.5..3....2.8..4.4....27.1
```
4. - [x] A small rating fix of Type 3 hidden (well known but I'll leave out)

5.  - [x] A fix for UL/UR sometimes not found
```
1..........34..2...2..5..3..1.3.6.....4.2.7.....5...8..3..6..9...2..78..........4
```
6. - [x] A fix for UR Type 3 Hidden Set sometimes not found
```
....2......74.69...8.....3.2.......1.3.9.5.4...8...6...5..1..9...2...4......9....
..1...2.....3.2...4...1...3.6.7.8.5...4...9...8.6.4.2.9...6...7...8.7.....5...1..
```
7. - [x] Fix for some BUG 3 selection error
```
Examples of puzzles affected by the bug
..9..6..3.3.....7.1...5.8.....6.3..2..6...9..3..7.4.....1.8...5.6.....2.8..2..1..
.1...2...34.........5.36......7..8.9..2...3..9.6..5......19.7.........43...8...5.
```

I'll compare the files with changes with serate121 code 1st then compare with lksudoku branch code to see if aligning/merging is possible. Issue hopefully to resolve in the next 4 days

**Comment by dobrichev** [comment]
Excellent. Feel free to ask for help understanding what I have changed and why.
If possible, leave a flag that switches between "old, buggy, but widely accepted" and "fixed" code.

**Comment by SudokuMonster** [comment]
@dobrichev. I'm struggling with aligning to chaining.java. I managed most of the code except this part
```
                assert !removable.isEmpty();
//From here==========================
                            // lksudoku: We sort the removable potentials so that all runs will yield the 
                            // same resulting chains, if not sorted, same puzzle may get different chains
                            // when there are different chains for same contradition, thus causing different
                            // rating of same puzzle at different times
							List<Cell> sortedRemKeys=new ArrayList<Cell>(removable.keySet());
					        Collections.sort(sortedRemKeys, new Comparator<Cell>() {
					            public int compare(Cell c1, Cell c2) {
					            	if (c1.getX() != c2.getX())
					            		return c1.getX() - c2.getX();
					            	if (c1.getY() != c2.getY())
					            		return c1.getY() - c2.getY();
					            	return c1.getPotentialValues().nextSetBit(0)-c2.getPotentialValues().nextSetBit(0);
					            }
					        });

                            for (Cell cell : sortedRemKeys) {
//To here ===============================
                                BitSet values = removable.get(cell);
```

**Comment by SudokuMonster** [comment]
2,4,5,6,7 all aligned now

**Comment by dobrichev** [comment]
The above part of code takes container that holds key - value pairs of type {cell, something}.
It copies only cells, sorts them by criteria (x, y, smallest active pencilmark).
The following loop is over the sorted cells and their respective value taken from initial container.
Since x has higher priority than y, a transposed grid is formed.

You may copy/paste the changed code in comment on the proper place. I will justify it an see if it makes sense.

**Comment by SudokuMonster** [comment]
I'll upload both chaining.java and potential.jave later with a comment

**Comment by SudokuMonster** [comment]
SE121 code:
```
            try {
                rule.getHints(grid, new HintsAccumulator() {
                    public void add(Hint hint0) {
                        IndirectHint hint = (IndirectHint)hint0;
                        Collection<Potential> parents =
                            ((HasParentPotentialHint)hint).getRuleParents(source, grid);
                        /*
                         * If no parent can be found, the rule probably already exists without
                         * the chain. Therefore it is useless to include it in the chain.
                         */
                        if (!parents.isEmpty()) {
                            ChainingHint nested = null;
                            if (hint instanceof ChainingHint)
                                nested = (ChainingHint)hint;
                            Map<Cell,BitSet> removable = hint.getRemovablePotentials();
                            assert !removable.isEmpty();
                            for (Cell cell : removable.keySet()) {
                                BitSet values = removable.get(cell);
                                for (int value = values.nextSetBit(0); value != -1; value = values.nextSetBit(value + 1)) {
                                    Potential.Cause cause = Potential.Cause.Advanced;
                                    Potential toOff = new Potential(cell, value, false, cause,
                                            hint.toString(), nested);
                                    for (Potential p : parents) {
                                        Potential real = offPotentials.get(p);
                                        assert real != null;
                                        toOff.parents.add(real);
                                    }
                                    result.add(toOff);
                                }
                            }
                        }
                    }
                });
            } catch(InterruptedException ex) {
                ex.printStackTrace();
            }
```
Fixed14 code:
```
            try {
                rule.getHints(grid, new HintsAccumulator() {
                    public void add(Hint hint0) {
                        IndirectHint hint = (IndirectHint)hint0;
                        Collection<Potential> parents =
                            ((HasParentPotentialHint)hint).getRuleParents(source, grid);
                        /*
                         * If no parent can be found, the rule probably already exists without
                         * the chain. Therefore it is useless to include it in the chain.
                         */
                        if (!parents.isEmpty()) {
                            ChainingHint nested = null;
                            if (hint instanceof ChainingHint)
                                nested = (ChainingHint)hint;
                            Map<Cell,BitSet> removable = hint.getRemovablePotentials();
                            assert !removable.isEmpty();
                            // lksudoku: We sort the removable potentials so that all runs will yield the 
                            // same resulting chains, if not sorted, same puzzle may get different chains
                            // when there are different chains for same contradition, thus causing different
                            // rating of same puzzle at different times
                            List<Cell> sortedRemKeys=new ArrayList<Cell>(removable.keySet());
                            Collections.sort(sortedRemKeys, new Comparator<Cell>() {
                                public int compare(Cell c1, Cell c2) {
                                    if (c1.getX() != c2.getX())
                                        return c1.getX() - c2.getX();
                                    if (c1.getY() != c2.getY())
                                        return c1.getY() - c2.getY();
                                    return c1.getPotentialValues().nextSetBit(0)-c2.getPotentialValues().nextSetBit(0);
                                }
                            });

                            for (Cell cell : sortedRemKeys) {
                                BitSet values = removable.get(cell);
                                for (int value = values.nextSetBit(0); value != -1; value = values.nextSetBit(value + 1)) {
                                    Potential.Cause cause = Potential.Cause.Advanced;
                                    Potential toOff = new Potential(cell, value, false, cause,
                                            hint.toString(), nested);
                                    for (Potential p : parents) {
                                        Potential real = offPotentials.get(p);
                                        assert real != null;
                                        toOff.parents.add(real);
                                    }
                                    result.add(toOff);
                                }
                            }
                        }
                    }
                });
            } catch(InterruptedException ex) {
                ex.printStackTrace();
            }
```
130f0de code:
```
            try {
                rule.getHints(grid, new HintsAccumulator() {
                    public void add(Hint hint0) {
                        IndirectHint hint = (IndirectHint)hint0;
                        Collection<Potential> parents =
                            ((HasParentPotentialHint)hint).getRuleParents(source, grid);
                        /*
                         * If no parent can be found, the rule probably already exists without
                         * the chain. Therefore it is useless to include it in the chain.
                         */
                        if (!parents.isEmpty()) {
                            ChainingHint nested = null;
                            if (hint instanceof ChainingHint)
                                nested = (ChainingHint)hint;
                            Map<Cell, BitSet> removable = hint.getRemovablePotentials();
                            assert !removable.isEmpty();
                            //for (Cell cell : removable.keySet()) {
                            for (Map.Entry<Cell, BitSet> entry : removable.entrySet()) {
                                //BitSet values = removable.get(cell);
                                Cell cell = entry.getKey();
                                BitSet values = entry.getValue();
                                for (int value = values.nextSetBit(0); value != -1; value = values.nextSetBit(value + 1)) {
                                    //Potential.Cause cause = Potential.Cause.Advanced;
                                    Potential toOff = new Potential(cell, value, false, Potential.Cause.Advanced, hint.toString(), nested);
                                    for (Potential p : parents) {
                                        Potential real = offPotentials.get(p);
                                        assert real != null;
                                        toOff.parents.add(real);
                                    }
                                    result.add(toOff);
                                }
                            }
                        }
                    }
                });
            } catch(InterruptedException ex) {
                ex.printStackTrace();
            }
```

**Comment by SudokuMonster** [comment]
I put lksudoku's declared fixes/enhancements mentioned on the forums on wiki page for reference
https://github.com/SudokuMonster/SukakuExplainer/wiki/lksudoku-SE-fixes

**Comment by SudokuMonster** [comment]
here is the counter example of Fixed14 effects on chaining
```
100200003040000050003006700002000008030070040900000100008400600050000020600003009
9.7/9.7/9.4 becomes 9.7/9.7/9.5 after fix
```
the code has been hidden with ability to switch "on" from Setting.java

**Comment by SudokuMonster** [comment]
There are 2 serate enhancements of interest:
```
f.
Added a command line option for serate to rate puzzles in batch mode, where all
lowest rating hints of same rating are applied concurrently, to use this mode add
the argument -b or --batch to serate command line

command line option description:

  -b, --batch
      Batch mode rating, apply all lowest rating hints of same rating
      concurrently intead of applying one lowest rating hint step only.

h.

  --techs=TECHSTRING
      Specific techniques only, set which techniques to use
      the techniques string TECHSTRING is a string consisting of the letters
      '0' and '1',where '1' means the technique should be used and '0' means
      it should not be used
      To see which technique is in which letter, and how many techniques are
      there, just type --techs= without any string after the = in TECHSTRING.
```

**Comment by dobrichev** [comment]
@SudokuMonster can you propose a plan with further steps for finalization of these improvements?

**Comment by SudokuMonster** [comment]
@dobrichev All fixes have been processed and have been either integrated or rejected. The chaining bugfix (rejected) is available as a hidden option activated from settings.

f. and h. enhancements have been partially implemented in the branch (Solver mainly and currently compile successfully) I will align then attempt changes to serate as they are controlled from the command line point; and test over the next 2-7 days

this issue hopefully can be closed after that

**Comment by dobrichev** [comment]
My point was whether I can contribute, not to close the issue now.
- Chaining bug fix - actually we rejected the wrong way in fixing it. The issue is still open. See below.
- "f" enhancement - the things are tricky, what is "all lowest rating", and, more interesting, what is "same rating".

This turns us back to the fundamental question whether two eliminations with equal (rounded to tenths) numerical representation of the rating, are equal or not.

The morphing issues can be simply resolved by solving a canonicalized puzzle but I am against such approach because it resolves only the numerical part of the problem. Other approach is applying specific families of techniques only in a batch. I am not sure whether this can resolve all cases, but hope so.

**Comment by SudokuMonster** [comment]
Chaining detection bug fix attempts to sort chains according to length and chooses shortest. It will still be susceptible to morphing variation.

Batch solving Accummulates all techniques that share the lowest rating for that move before applying all. This in theory should eliminate morphing issues. It would however apply potentially different chain types if the share the same rating.

There was a discussion somewhere that escapes me now but the consensus is that canonicalization would be the only way to eliminate the morphing problem regardless of how well chain selection/Batching/sorting is.

The chain length sorting fix is in the background for you to look at.

I'll report back with an update about the enhancements f & h

**Comment by dobrichev** [comment]
> Chaining detection bug fix attempts to sort chains according to length and chooses shortest. It will still be susceptible to morphing variation.

Literally yes, but if "length" is replaced by "rating modifier", then no. IMO the right way is to accumulate the rating during the chain search and cancel the process as soon as the rating exceeds the already found simplest elimination.

> Batch solving Accumulates all techniques...

Agree to try this not only for speed but also for determinism.

> ...canonicalization would be the only way to eliminate the morphing problem...

This is true only if you don't care precisely for techniques but want to be sure that morphing the puzzle for reaching higher rating wouldn't work. In general I disagree with such approach.
If in the rating process choices like "first cell", "smallest candidate", "rows then columns", etc. are **never** used, the rating will be deterministic and insensitive to morphing. When it isn't possible to choose which elimination to apply (from eliminations having exactly the same rating), then apply them all at once.

**Comment by SudokuMonster** [comment]
I think there is room for both ...
Batch solving being an option; it can then be tested in the presence and abscence of canonicalization.
If Batch solving has the same results in both situations then canonicalization can be then used. If we are going to use a breadth type search and application of solution techniques then use canonicalization with it. If we are using depth type (batch) search and application then canonicalization can be removed

**Comment by SudokuMonster** [comment]
@dobrichev I've got the batch mode working now in the branch lksudoku14.
new options:
```
--batch (-B) activates batch mode
--newRating (-N) activates new rating scheme
--lksudokuChaining (-C) activates lksudoku chain length bug fix
```
I'm looking now at the point .h (--techs=TECHSTRING) enhancement now! if all is good it can be merged with Master

**Comment by dobrichev** [comment]
Excellent!

Few remarks
- I would rename newRating to something else to avoid further new_new_new_rating. Say --ratingscheme=1.
- same for chaining.
- same for batch - this mode can be further improved by directly applying all eliminations below maximal ER in arbitrary order.
- think about extension allowing, when storing rating results into file, to write (in the puzzle start section?) the active parameters that change the ratings. Most trivial solution for serate mode is to write on single line the version and all command-line parameters except the puzzles. W/o such info you are never sure how exactly the yesterdays puzzles/batch were rated.
- I have a (likely unrealizable) dream to consolidate the unnecessarily split logic from rules, hints, hint producers, etc. into more compact form, defining a full table with rules, and extracting the rating formulas from all different pieces of code into a single table. All these patches and conditional ratings complicate this task. Your experience in rating formulas would be very helpful in extending the rules.ods sheet.

**Comment by SudokuMonster** [comment]
>this mode can be further improved by directly applying all eliminations below maximal ER in arbitrary order.

I'll see if this can be simply done by changing:
```
} else if ( ((Rule)hint).getDifficulty() != dif ) {
```
to:
```
} else if ( ((Rule)hint).getDifficulty() > difficulty ) {
```
>think about extension allowing, when storing rating results into file, to write (in the puzzle start section?) the active parameters that change the ratings. Most trivial solution for serate mode is to write on single line the version and all command-line parameters except the puzzles. W/o such info you are never sure how exactly the yesterdays puzzles/batch were rated

That is true. (batch newRating lksudokuChaining and techs)

**Comment by SudokuMonster** [comment]
lksudoku's fixes / enhancements have now been integrated
The latest branch merge has all the details

**Comment by SudokuMonster** [comment]
The following puzzles show a difference between B1 and B2 ratings. All the puzzles that showed this difference had a lower B1 rating, this suggests some error in applying B. This requires a further look at the B2 change in code to see if it is correct
```
2..3....1....7.2....74...8.1.3.6...5.5.8..9.......3....7..9.6....2....5.8..6....4;312;045;08.7;08.3;07.8;m_b_metcalf
1....23...4..5..6...27....8..6.91....5.2.....2..8..6..8....7..6.9.....4...3...1..;314;111;10.8;10.8;08.9;champagne
.....1..2....3..4...14..5....67...2..3..5...41....38....5..8....4.6....72...7..9.;192;089;05.9;04.0;03.4;champagne
..6.1.7...9...5.2.8.......4.......8.1...2.6...4......57...6...2.5.4...3...3..21..;128;133;05.8;03.8;03.4;ronk
.....1..2.3.....4...567......1..36....8.2....9..5........8..5...4.....9.2.......3;084;041;08.7;07.2;02.6;m_b_metcalf
..1.....2.3...2.4.5.....6.......3.7.....8...5.9.7.4.....6...1...4.9...2.1...2...8;081;086;10.8;10.8;07.1;JPF
..9.....8.7...6.5.4...3.9.......1....3..6..1....7.......2.5...4.1.6...7.8.....2..;097;084;09.8;09.8;08.9;champagne
1...2...3.4.....5...6.7.8.....2.9...3.5...9.1...6.3.....4.8.5...1.....4.2...6...7;018;087;09.3;02.3;02.3;JPF
.1.......2.....3.....4.567...38.61.............57.29...826.1.....7....5.........9;043;043;05.7;03.4;03.4;JPF
..1..2..3....1..4.5..6..7....2..8..5.7.....6.3..9..2....9..5..7.8..4....2..3..8..;124;142;11.2;11.2;10.5;Mauricio
1....2..3.4..5.6.....7...8...91....2.2..7.1..3....5....8..6.7....6....4.5..9....6;351;079;10.9;10.9;10.7;champagne
...1...2...3...4...5..4...67..6...8...4.5.3.......9....2..6..5.1..7..8....8.....9;080;040;10.0;10.0;08.8;m_b_metcalf
..12.34...2.....8.3...6...27..3.4..1..4...7..5..7.6..42...3...9.9.....1...79.52..;038;084;08.1;08.1;06.6;gsf
.....9.87....7.695...6..43...8..4..3.5.....7.2..1..5...95..2...823.1....16.8.....;155;101;07.8;07.8;07.5;champagne
1.2...3.......4.1.5...1...6...4...7...6.2.5...8...7...6...5...9.9.8.......3...1.2;102;079;10.0;07.2;07.2;JPF
1.2...3...4.....5.5....26.4...2.17......8......93.4...7.19....3.8.....7...4...1.6;085;025;09.9;09.8;09.3;m_b_metcalf
.....5..7.4.....5...2.9.3......6..9...52..4..3....1..6..6.7.....8.4...2.4....8..1;130;020;08.5;07.3;03.0;gsf
.....82...1..2..8....6....7..69......3...1...4...3..2.9.....7...8...3.5...7.....6;086;084;08.0;06.7;06.7;gsf
.5...1...3...4.5.........9.....7...8.9.8.6.1.2...5.7...3...4.....4.6...7...7...8.;178;037;07.8;02.8;02.6;gsf
1..2....3.3.....4...5..67....2.....7.1..8..9.6.....1....14..3...9.....8.3....5..6;241;002;10.3;09.8;09.3;champagne
.1.7....2....3..8...6...4...8...9.....4....6.5..2....7....8.3..7....5..1.2.9.....;344;046;10.2;09.5;03.4;1to9only
```

**Comment by dobrichev** [comment]
I didn't look at B2 implementation but expect that it inherits all drawbacks of B1 plus possibly other. Applying the decisions on how to process B1 (which is the "right" rating) could automatically resolve the B2 issues. In other words, this behaviour is quite possible to be not an implementation bug.

**Comment by SudokuMonster** [comment]
@dobrichev, I agree with you that issues from B1 will be inherited by B2 and independent testing in the future would help. On this occasion due to an oversight I noticed that the difference between B1 & B2 ratings was due to the fact that Max difficulty is updated after hint accumulation not during. This means that if lowest rated hint(s) available exceed Max dificulty then hints will be applied one at a time rather than in batch. I fixed this by applying what B1 does at this stage.
```
(((Rule)hint).getDifficulty() > difficulty && ((Rule)hint).getDifficulty() != dif && Settings.getInstance().batchSolving() == 2)
``` 
The 25 puzzles now have B1,B2 identical ratings and B2 is quicker overall

**Comment by dobrichev** [comment]
@SudokuMonster , I edited your opening comment (yes, it is possible and maybe not a good practice) and added flags "done" on all items except the third.

For the third item
`3. There is chain sorting improvement aimed at guaranteeing the same chain output everytime`
I see 3 places in Chaining.java where you added conditional processing via 
`if (Settings.getInstance().Fixed14Chaining() == 1)`

Place 1) In getOnToOff if the only change is in the declaration of the result
```
LinkedSet<Potential> result = new LinkedSet<Potential>(); //new
Set<Potential> result = new LinkedHashSet<Potential>(); //original
```
then we can use LinkedSet safely and remove the whole conditional block.

Place 2) In doChaining if the change is in accumulation of contradiction chain and exporting only the shortest one, we can
- check using existing modification whether we can find case where the shortest chain isn't the first. If such cases exist we can go further and
- move the change outside of the loop, this guaranteeing that the shorter within ALL POSSIBLE chains is exported.

Place 3) In getAdvancedPotentials - is is still unclear and must be left off. Unification of all similar containers, possibly using dedicated custom container with more fields, should be the focus.

**Comment by SudokuMonster** [comment]
No problem. It actually looks nicer. I just made the code changes conditional without looking into what would happen if they were left without …

This is the example where I assumed the fix picked a longer chain
```
100200003040000050003006700002000008030070040900000100008400600050000020600003009   9.7/9.7/9.5 DDFC+/DDFC+/DCFC
```
original rating should be:
```
100200003040000050003006700002000008030070040900000100008400600050000020600003009   9.7/9.7/9.4 Patrice
```
I reported it but didn't investigate any further

**Comment by dobrichev** [comment]
The higher rating for the above example comes from getOffToOn() modification, Place 4), in line
`if (pOn.getAncestorCount() < pCell.getAncestorCount()) {`
AncestorCount is only one of the several factors that determine final rating. Others include the isYChainEnabled, LengthDifficulty which itself depends on FlatComplexity(AncestorCount) and NestedComplexity. Assumption that for the eventual hint all other factors are equal seems wrong.
There is plenty of similar assumptions in the original code too.

Disabling this particular fix leaves the sequence of the iterations to dictate which of the potentials to be taken and this isn't good to.

The cure is drastic change in whole rating schema, targeting the lowest possible rating at every step.

**Comment by dobrichev** [comment]
The test case for Place 4) partially answered my question for feasibility of the fix on Place 2). Likely examples for rating change in both directions can be found, and this doesn't resolve the problem.

**Comment by dobrichev** [comment]
Since in the near future there is no expected activity for resolving the remaining issues from above discussion, I propose
- removal of the code in Chaining.java enclosed by 
`if (Settings.getInstance().Fixed14Chaining() == 1) { ... }`
- removal of the `Fixed14Chaining` and related from Settings.java
- closing this issue

I am examining eventual data model changes and every unnecessary line of code adds noise where it is easy to get lost.

**Comment by SudokuMonster** [comment]
> Since in the near future there is no expected activity for resolving the remaining issues from above discussion, I propose
> 
> removal of the code in Chaining.java enclosed by
> if (Settings.getInstance().Fixed14Chaining() == 1) { ... }
> removal of the Fixed14Chaining and related from Settings.java
> closing this issue
Fixed14chaining and related code has been removed.
I added -G and -U command line options to control the BUG and UR/UL fixes (which should allow the backward compatibility with SE121)
